# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: prisma-template
    ports:
      - '33062:3306'
    environment:
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: template
